### ISSUE TITLE
Ring-only view on tap

### ISSUE THREAD

**Issue by chris1010010** [smplifenathan/minimal-rings#4]
Since tapping is not used at the moment, would it be possible to zoom in to the rings on single tap? This could hide the clock. Another tap could restore the view.
Very nice clock face!

**Comment by nathanatkinson22** [comment]
Thanks for the feedback and suggestion. This is something I'll have to look into, but I like this idea!

**Comment by nathanatkinson22** [comment]
I've added this and submitted the next version for review. It should be available in the next week or two.

**Comment by chris1010010** [comment]
Very nice!!!
It auto-updated...
